include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  errors:
    invalid_annotation_target: ignore

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Security
    avoid_print: true
    avoid_web_libraries_in_flutter: true

    # Performance
    avoid_slow_async_io: true
    use_build_context_synchronously: true

    # Code Quality
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    require_trailing_commas: true

    # Flutter specific
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true
