name: e_atv
description: "Mark-2 Controller for Mini-E-ATV 2.0"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  flutter_blue_plus: ^1.35.5
  permission_handler: ^11.0.1
  wifi_scan: ^0.4.1+2
  connectivity_plus: ^4.0.0
  web_socket_channel: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/pndipda.png"

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
